[package]
name = "kmers"
version = "0.1.0"
authors = ["Erik Clarke <erikclarke@fastmail.com>"]

[dependencies]
bio="0.13.0"
bit-vec="0.4.3"
byteorder="1.0.0"
error-chain="0.10.0"
itertools="0.5.10"
num="0.1.37"
num-bigint="0.1.37"
num-traits="0.1.37"
vec_map="0.7.0"